.TH YADTshell 1 "November 18, 2013" "YADTshell User Manuals"
.SH NAME
.PP
yadtshell \- yadt, an augmented deployment tool: the shell part
.SH SYNOPSIS
.PP
yadtshell \f[I]command\f[] [\f[I]options\f[]][*component*]...
.SH DESCRIPTION
.PP
yadtshell allows you to control services and deployments, regarding the
dependencies across the whole data center.
The hosts to handle are taken from the \f[I]target\f[] file in the
current directory.
.SH COMPONENTS
.IP \[bu] 2
services : service://\f[I]host\f[]/\f[I]servicename\f[]
.IP \[bu] 2
artefacts :
artefact://\f[I]host\f[]/\f[I]artefactname\f[]/\f[I]version\f[]
.IP \[bu] 2
hosts : host://\f[I]host\f[]
.PP
(Wildcards \f[C]*\f[] and \f[C]?\f[], and ranges \f[C][start..end]\f[]
allowed)
.SH COMMANDS
.IP \[bu] 2
status : Retrieves the actual state of all target hosts (see also
https://github.com/yadt/yadtshell/wiki/Status\-Information)
.IP \[bu] 2
update [\f[I]HOSTS\f[]] : Updates the specified hosts / all hosts by
stopping related services and restarting them afterwards.
Guarantees that all services will be running after a successful updates.
.IP \[bu] 2
start \f[I]SERVICES\f[] : Starts all specified \f[I]SERVICES\f[],
regarding the correct order
.IP \[bu] 2
stop \f[I]SERVICES\f[] : Stops all specified \f[I]SERVICES\f[],
regarding the correct order
.IP \[bu] 2
info : Shows the last known state of the target, does not retrieve data
from hosts
.IP \[bu] 2
ignore \f[I]SERVICES\f[] : ignores the specified services all following
actions will be skipped and its results are always successfull
.IP \[bu] 2
updateartefact \f[I]ARTEFACTS\f[] : updates the specified artefacts, but
\f[I]disregarding any service dependencies\f[]
.IP \[bu] 2
lock \f[I]HOSTS\f[] : Locks the host(s), ensuring that only you can
perform operations on it.
Needs a message option.
.SH OPTIONS
.IP \[bu] 2
\-\-reboot : Reboots machines during an update, either if a pending
artefact is configured to induce a reboot, or if the machine is running
an outdated kernel.
If a set of host URIs was passed to the update command, then only those
hosts are eligible for a reboot.
.IP \[bu] 2
\-n : No operation: change nothing, just show what \f[I]would\f[] be
done (aka dryrun).
.IP \[bu] 2
\-p \f[I]P\-SPEC\f[] : Runs eligible operations in parallel.
See
https://github.com/yadt/yadtshell/wiki/Wave\-deployment\-with\-parallel\-actions
for more information.
.IP \[bu] 2
\-\-force : Ignores locks.
Valid only for the \f[C]lock\f[] command.
This allows for taking over a lock in order to release it.
.IP \[bu] 2
\-m \f[I]MESSAGE\f[] : Adds a message to a command.
Valid only for the \f[C]lock\f[] and \f[C]ignore\f[] commands.
.IP \[bu] 2
\-\-no\-final\-status : Do not query and display the \f[I]status\f[] of
the target after an action that changed it (e.G.
\f[I]start\f[], \f[I]update\f[], ...).
.SH EXAMPLES
.IP \[bu] 2
yadtshell status: retrieves the current state of your target
.IP \[bu] 2
yadtshell stop service://*/* : stops all services
.IP \[bu] 2
yadtshell update host://foo1 host://foo2 : updates both hosts
.IP \[bu] 2
yadtshell update host://foo1 \-\-reboot : updates or reboots (or
possibly both) but only on foo1
.IP \[bu] 2
yadtshell update \-\-reboot : updates (and possibly reboots) all servers
from the target
.IP \[bu] 2
yadtshell updateartefact artefact://foo1/some\-config : updates the
package \f[I]some\-config\f[] without regarding service dependencies
.SH SEE ALSO
.TP
.B the yadt project
http://www.yadt\-project.org/
.RS
.RE
.TP
.B sources at github
https://github.com/yadt
.RS
.RE
.TP
.B Alternatives
puppet, chef
.RS
.RE
.SH LICENSE
.PP
Licensed under the GNU General Public License (GPL), see
http://www.gnu.org/licenses/gpl.txt for full license text.
.SH AUTHORS
The YADT project team.
